#!/usr/bin/env sh

if [ "$#" -eq 1 ]; then
  if [ "$1" == start ] || [ "$1" == stop ] || [ "$1" == restart ]; then
    control_type=$1
  else
    echo "Usage: $0 start|stop|restart"
    exit
  fi
else
  echo "Usage: $0 start|stop|restart"
  exit
fi

if [ "$control_type" == stop ] || [ "$control_type" == restart ]; then
  echo "Stopping MongoDB instances"
  launchctl unload ~/Library/LaunchAgents/org.lyon-smith.mongodb1.plist
  launchctl unload ~/Library/LaunchAgents/org.lyon-smith.mongodb2.plist
  launchctl unload ~/Library/LaunchAgents/org.lyon-smith.mongos.plist
  launchctl unload ~/Library/LaunchAgents/org.lyon-smith.mongodb_shardconfig.plist
  pkill -f mongod
fi

if [ "$control_type" == start ] || [ "$control_type" == restart ]; then
  echo "Starting MongoDB instances"
  launchctl load ~/Library/LaunchAgents/org.lyon-smith.mongodb1.plist
  launchctl load ~/Library/LaunchAgents/org.lyon-smith.mongodb2.plist
  launchctl load ~/Library/LaunchAgents/org.lyon-smith.mongos.plist
  launchctl load ~/Library/LaunchAgents/org.lyon-smith.mongodb_shardconfig.plist
fi
